### PR TITLE
Fix #52 https://github.com/Moocar/logback-gelf/issues/52

### LINKED ISSUE #52: Feature Request: JMS or AMQP transport
Now that there is native support for AMPQ support in GrayLog, it would be really neat to be able to log messages using this technology.

JMS and AMPQ both have their advantages and disadvantages... JMS is protocol independent, so it'd run on a wide variety of Java platforms and servers. The other advantage is that this could like be implemented using provided dependencies, meaning that logback-gelf wouldn't bring in any transitive baggage. Since the server manages the connections, no connection information is specified in the configuration, just a target queue. The disadvantage, well its JNDI lookups. They're terrible. Example: http://grepcode.com/file/repo1.maven.org/maven2/ch.qos.logback/logback-classic/0.9.19/ch/qos/logback/classic/net/JMSQueueAppender.java#92

AMQP is a wire level protocol, so while would likely need a compile dependency on a Java AMQP library, this frees you from having to use a traditional Java server like tomcat, Glassfish, TomEE, Wildfly. You could connect straight to the server, but that means logging information is stored on a per application basis, which for some environments may pose a flexibility problem. 

Thanks for listening :) And great work on this implementation, it's awesome.

### PR DESCRIPTION
**Pull request by exabrial**
Fix #52 https://github.com/Moocar/logback-gelf/issues/52

### CODE REVIEW

**Comment by Moocar** [comment]
Thanks so much for this @exabrial! Since this involves pulling in an additional dependency (javax.jms/jms), I'd like to put this into a separate library that logback-gelf users can pull in if they need it. In the same way I do for the [TCP SocketAppender](https://github.com/Moocar/socket-encoder-appender). I'm happy to do this, but since you wrote this code, I wanted to give you the opportunity to own it if you like. If not, I'll go ahead and create a new repo.

**Comment by exabrial** [comment]
Well if you want to make it that complicated go ahead, this is a bit of a special case :) there's a bit more of a simplistic solution. Simply pull in the standardized Java EE api as a  `<provided>` dependency. This code will work on _any_ Java EE server, given the right JNDI lookups. If a user decides to use this piece of code, the implementations will be provided by the server when it loads the class, meaning there is no further dependencies needed.

**Comment by Moocar** [comment]
Nice, that will work nicely for Java EE users, but since it won't compile for normal JVM users, I'll put it in a separate repo with the javax.jms dependency.

**Comment by exabrial** [comment]
That's what I'm saying though... It'll still compile for normal (Non Java EE) users AND for normal (non Java EE Users) it will not bring in the JMS dependency

**Comment by exabrial** [comment]
Pom file updated. This will _compile_ but it will not pull the jar in at runtime. :)

**Comment by Moocar** [comment]
Right, but if a non JavaEE user wants to use this, they'll have to add jms onto their classpath manually. Whereas if we ship it as its own library, we can declare the jms dependency in that pom and also have full control over the version. It's also one less bit of code that non JMS users have to deal with.

**Comment by Moocar** [comment]
Also, I'm trying to test this. How do you declare a JMS input on Graylog server? I see an option for AMPQ, but not JMS.

**Comment by exabrial** [comment]
Anthony, I fully understand your concerns but I think you're failing to realize this solves exactly what you are asking for.

If a normal user were to bring the new jar into their project, they would _not_ have to declare a JMS dependency. Your project will continue to work as-is for non Java EE users. 0 changes. I promise. Don't believe me still? Try it yourself. Compile the code and drop it into one of your existing projects, the proof is in the pudding.

If said normal (non Java EE) user attempted to use the class in a non Java EE environment by declaring the JMS transport in their logback.xml, then _and only then_ would they receive an error... because JMS does not run outside of a Java EE server. And so it goes full circle... A normal user will not/cannot use JMS, and a Java EE user will have the classes on the classpath of the server. So... in either case, an extra dependency is not needed.

Theoretically, if you attempt to include the API dependency, this code would still be useless to a normal user because JMS is just an API and the implementation can only be provided by a Java EE server. So...

I suggest you just try it. It'll work. It does what you want, I promise.

**Comment by exabrial** [comment]
As for running it, there's serveral ways to do this... JMS is not a wire protocol specification, so you can't "have a JMS input" on graylog. Our message broker that implements the JMS spec just happens to speak AMPQ, so we created an endpoint for graylog to talk to and solved the problem.

Remember, JMS is just an abstraction for messaging... Under the covers (depending on your Java EE server) it could be AMPQ, MQTT, OpenWire, Protobuff, MQ Series, etc...

**Comment by Moocar** [comment]
Sure, I'm not arguing that non JMS users will run into issues. But JMS is an API that can be implemented by more than just a JavaEE container. I myself have written one that acts as a load balancer to a Tibco MQ. So there's more to think about here than just JavaEE.

You are right however that even just including the dependency will still render it useless since the implementation must be provided on the classpath anyway :). 

I'll try and find an AMPQ broker that implements JMS and run a few tests. Thanks again.

**Comment by exabrial** [comment]
Another way would be to write a message consumer on the JMS Queue and have it push messages to a GELF Connector on the server via TCP. We used to do that, if you'd like that code I could probably find it.

**Pull request closed without merging**
